-
  name: "Kraken"
  price_url: "https://api.kraken.com/0/public/Ticker?pair=XXBTZEUR,XXBTZUSD,XXBTZCAD,XXBTZGBP,XXBTZJPY"
-
  name: "Bitstamp"
  price_url: "https://www.bitstamp.net/api/ticker/"
-
  name: "BTC-e"
  price_url: "https://btc-e.com/api/3/ticker/btc_usd-btc_eur"
